[package]
name = "getting-farted-on"
version = "0.1.0"
edition = "2021"

[dependencies]
geng = "0.13"
serde = "1"
noise = "0.7"

[build-dependencies]
cmake = "<=0.1.45" # https://github.com/PistonDevelopers/freetype-sys/issues/99