name: CI
on: push
env:
  CONNECT: singleplayer

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - run: rustup target add wasm32-unknown-unknown
      - run: sudo apt-get update && sudo apt-get install -y libasound2-dev
      - name: Install cargo-geng
        run: cargo install cargo-geng --version ^0.13
      - name: Install wasm-bindgen
        run: cargo install wasm-bindgen-cli --version 0.2.83
      - run: cargo geng build --release --target wasm32-unknown-unknown --index-file game.html
      - name: Upload artifacts (web)
        uses: actions/upload-artifact@v2
        with:
          name: web
          path: target/geng
      - run: cargo geng build --release
      - name: Upload artifacts (linux)
        uses: actions/upload-artifact@v2
        with:
          name: linux
          path: target/geng

  deploy:
    name: Deploy
    if: github.ref == 'refs/heads/jam-version' && github.repository_owner == 'kuviman'
    runs-on: ubuntu-latest
    needs:
      - build
    environment:
      name: jam-version
      url: https://kuviman.github.io/getting-farted-on/jam/
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: web
          destination_dir: play/jam
